trigger:
  - main

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8199a986-94fb-44c8-8130-c9162de7c60d'
  imageRepository: 'springhelloworld'
  containerRegistry: 'ndacrsnd.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: 'latest'
  vmImageName: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildSpring
        displayName: Build Spring
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Maven@3
            displayName: 'Building Spring'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'
          - script: echo "Spring build completed."
            displayName: 'Spring Build Completed'

      - job: BuildDockerImage
        displayName: Build Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: 'Build and push an image to container registry'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)


  - stage: Deploying
    displayName: Deploying to EC2
    jobs:
      - job: DeployEC2
        displayName: Deploy EC2
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: echo "Deploying to EC2..."
            displayName: 'Deploy to EC2'
